sudo: false
dist: bionic
language: generic

git:
  depth: 3

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
      env:
        - BUILD_TARGET=linux
        - COMPILER=g++
    - compiler: clang
      env: BUILD_TARGET=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - clang
      env:
        - BUILD_TARGET=linux
        - COMPILER=clang++
    - compiler: x86_64-w64-mingw
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64 
      env:
        - BUILD_TARGET=win64

script:
  - if [ "$BUILD_TARGET" = "linux" ]; then
      ./build-linux.sh;
    elif [ "$BUILD_TARGET" = "win64" ]; then
      ./build-cross-linux-to-mingw.sh;
    fi

notifications:
  email:
    - alien-av@users.noreply.github.com

before_deploy:
  - if [ "$BUILD_TARGET" = "linux" ] && [ "$COMPILER" = "g++" ]; then
      cmake --build build-linux/ --target create_zip --;
    elif [ "$BUILD_TARGET" = "win64" ]; then
      cmake --build build-cross-linux-to-mingw/ --target create_zip --;
    fi

deploy:
  skip_cleanup: true
  file_glob: true
  provider: releases
  api_key:
    secure: lHYmqlwpSBrv38ATtNJRcLLGZd6QbjyP8S5u3EJAkL7lkSUVhoodL+ao10Cvxq/EnfRnMvBITv72cMPavfKn9dDg3QzWfbwrStsmKzfkcm4Rqg+BtUievdVZX4NKPWAlb2aXZoRTxTm/uWnZv15Fukir2Y2h/47xUI9Nbpl1cfBimAyEI2KobetkCb8wW42BQuh7GzwkYCP2st7dCI/UahnEj71hYTKOa/Oww8/cCcHJLZxEiEl1cQVdcGXe5F3wtti4mu84VGNBQKxF91Qg4mFvHodV8vSUzNQeFf2vBs583K/Df8qj2oIZL9DAGPid6mxDc0kie+019WYeDFFoX5gmxMtJEcjWQ2FC4RwvQdOgJay4uF31GIk0ozs+8pa9kqeIRK9qO8PY5Amy4rCO2/i0zVIu0/CBNNLyw97oUBcmbC7cnB2/T2Mtz1eVVxoDASn0d3qE2PZgzYpW27OMH06QurxqE1rERj61Y7MRHhCtO1RIikXr/pnH2Lh6SnXY8et+xPF2rQxMxyAv7VP8sOhOQ3WVMuYUUVm5ZgHPWflstayXpNXGFXd1Xf140MvsYRMqbG/sGm9PK/2zTY2+cWgKnn+smIwVF6VCk6IC9eTbd2l1RWrQEH9zMS+0i58HRXdK5L89RY8rtmGAmTYpDdYqBMsXYSHTkLC4TMdPdz8=
  file: crimesquad*.zip
  on:
    repo: Alien-AV/Liberal-Crime-Squad
    tags: true

