sudo: false
dist: trusty
language: generic

git:
  depth: 3

branches:
  only:
  - master

matrix:
  include:
    - compiler: gcc
      env: BUILD_TARGET=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      env: BUILD_TARGET=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-5
            - clang-4.0
      env: COMPILER=clang++-4.0
  allow_failures:
    - compiler: x86_64-w64-mingw
      env: BUILD_TARGET=win64
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64 

before_script:
  - autoconf --version
  - automake --version
  - mkdir build
  - cd build
  - if [ "$BUILD_TARGET" = "linux" ]; then
      ../bootstrap CXX=$COMPILER --disable-silent-rules
    elif [ "$BUILD_TARGET" = "win64" ]; then
      ../bootstrap --host=x86_64-w64-mingw32  --disable-silent-rules
    fi

script:
  - make

notifications:
  email:
    - bregma@users.noreply.github.com
