sudo: false
dist: bionic
language: generic

git:
  depth: 3

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
      env:
        - BUILD_TARGET=linux
        - COMPILER=g++
    - compiler: clang
      env: BUILD_TARGET=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - clang
      env:
        - BUILD_TARGET=linux
        - COMPILER=clang++
    - compiler: x86_64-w64-mingw
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64 
      env:
        - BUILD_TARGET=win64

script:
  - if [ "$BUILD_TARGET" = "linux" ]; then
      ./build-linux.sh;
    elif [ "$BUILD_TARGET" = "win64" ]; then
      ./build-cross-linux-to-mingw.sh;
    fi

notifications:
  email:
    - alien-av@users.noreply.github.com
