sudo: false
dist: bionic
language: generic

git:
  depth: 3

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
      env:
        - BUILD_TARGET=linux
        - COMPILER=g++
    - compiler: clang
      env: BUILD_TARGET=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - clang
      env:
        - BUILD_TARGET=linux
        - COMPILER=clang++
    - compiler: x86_64-w64-mingw
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64 
      env:
        - BUILD_TARGET=win64

before_script:
  - mkdir build
  - cd build
  - if [ "$BUILD_TARGET" = "linux" ]; then
      ../bootstrap CXX=$COMPILER --disable-silent-rules;
    elif [ "$BUILD_TARGET" = "win64" ]; then
      ../bootstrap --host=x86_64-w64-mingw32  --disable-silent-rules;
    fi

script:
  - make -j2
  - if [ "$BUILD_TARGET" = "linux" ]; then
      make check;
    fi

notifications:
  email:
    - bregma@users.noreply.github.com
